 *Luis Antonio Ortega Andrés     
Antonio Coín Castro*

# Cuestiones previas

**Pregunta 1.** ¿Dado un conjunto de $n$ puntos, existe siempre un polinomio de grado $m < n-1$ que pase por dichos puntos?

No

**Pregunta 2.** ¿Se te ocurre una manera en la cual el cálculo de los valores singulares de una matriz permita calcular un polinomio de regresión adecuado?

No


**Pregunta 3.** ¿Como podrías transformar el problema de encontrar un polinomio de regresión en un problema de producto de matrices?

No podría.


**Pregunta 4.** ¿Crees que, además, es posible calcular el error de regresión a partir de los valores singulares?

No


# Ejercicios

## Apartado 1

Considera los sigiuentes conjuntos de puntos:

In [52]:
x = [0, 0.25, 0.5, 0.75, 1]
y = [1, 1.2840, 1.6487, 2.1170, 2.7183]

Vamos a buscar el polinomio $P_2(x) = a_0 + a_1x + a_2x^2$ que minimiza el error al aproximar los datos anteriores usando la norma estándar de $\mathbb{R}^n$. Es decir, vamos a usar una regresión cuadrática.

- Vamos a escribir el problema de regresión como un problema de interpolación sobredimensionado asumiendo que el polinomio $P2(x)$ pasa por todos los puntos $x_i,y_i$. Para ello escribiremos el problema en la forma $Xa = y$ donde $X$ es una matriz $5 \times 3$, $a$ es un vector $3 \times 1$ e $y$ es un vector $5 \times 1$. 

In [59]:
import numpy as np
X = np.vander(x, 3, increasing=True)
print(X)

[[1.     0.     0.    ]
 [1.     0.25   0.0625]
 [1.     0.5    0.25  ]
 [1.     0.75   0.5625]
 [1.     1.     1.    ]]


- Calculad la descomposición en valores singulares $X = U S V^T$ de la matriz $X$ que habéis encontrado en el apartado anterior. Utilizad los apuntes de clase para obtener los valores singulares de $X$ y para construir las matrices $U$ de $5\times 5$, $S$ de $5\times 3$ y $V$ $3\times3$.

In [60]:
U, S, V = np.linalg.svd(X)

In [61]:
print(U)

[[-0.29454913  0.63267484  0.63140925 -0.02576091 -0.33707876]
 [-0.346616    0.45500901 -0.21036331  0.28091869  0.74138797]
 [-0.41593037  0.19422733 -0.52439676 -0.68819061 -0.20169135]
 [-0.50249224 -0.14967019 -0.3106911   0.63666879 -0.47246617]
 [-0.60630161 -0.57668356  0.43075367 -0.20363596  0.26984831]]


In [62]:
print(S)

[2.71168512 0.93707467 0.16268803]


In [63]:
print(V)

[[-0.7987245  -0.4712162  -0.37415833]
 [ 0.59286357 -0.51017309 -0.62308604]
 [ 0.10272272 -0.71949893  0.68685467]]


## Apartado 2

Se puede demostrar (de hecho, no es muy difícil), que los valores $a = (a_0, a_1, a_2)$ del polinomio que buscamos se pueden obtener mediante el siguiente producto de matrices
$$
a = Vz
$$
El vector $z = (c_1/s_1, c_2/s_2, c_3/s_3)$, donde los valores si corresponden a los valores singulares de la
matriz $X$ y los valores $c_i$ corresponden a los tres primeros valores del vector obtenido al
multiplicar la matriz $U^T$ por $y = (y_1, y_2, y_3, y_4, y_5)$.

Algo como (teniendo en cuenta vectores completos en lugar de los que da python):
$$
USV^T a = y
$$
$$
SV^Ta = U^Ty
$$
$$
V^T a = S^{-1}U^Ty = z \implies a = Vz = VS^{-1}U^Ty
$$


In [66]:
c = U.T@y
z = c[:3]/S
a = V.T@z

In [67]:
X@a

array([1.00513714, 1.27391143, 1.64814286, 2.12783143, 2.71297714])

Algo no funciona. X@a deberia ser "y"

## Apartado 3

Apartado 3: Se puede demostrar también (es más fácil aun) que el error cometido con la regresión obtenida para los valores es $E = \sqrt{c_4^2 + c_5^2}$, calculad el error y comparadlo con el cálculo manual del error 
$$
\sqrt{\sum_{i=1}^5 (P_2(x_i) - y_i)^2}
$$

In [39]:
e_t = np.sqrt(c[3]**2 + c[4]**2)

In [40]:
e_r = np.sum((X@a - y)**2)

In [41]:
print(e_t)

0.016556949339433746


In [42]:
print(e_r)

5.830295835955804


# Ejercicio opcional

- ¿Qué obtenemos cuando aplicamos el método de los apartados 1 y 2 a la construcción de un polinomio de grado 4?
- Comprueba que, efectivamente el polinomio obtenido se corresponde en este caso a un polinomio de interpolación en lugar de a un polinomio de regresión.

In [43]:
X = np.vander(x, 4, increasing=True)
print(X)

[[1.       0.       0.       0.      ]
 [1.       0.25     0.0625   0.015625]
 [1.       0.5      0.25     0.125   ]
 [1.       0.75     0.5625   0.421875]
 [1.       1.       1.       1.      ]]
